server:
  port: 7987

spring:
  application:
    name: debug4j-server
  web:
    resources:
      static-locations: "classpath:/dist"

debug4j:
  key: k4ln
  socket-port: 7988

sa-token:
  http-basic: 'k4ln:123456'
  max-login-count: -1

